"""add users and manual action links

Revision ID: ea5708e7e72d
Revises: adc0352cad95
Create Date: 2026-10-01 15:45:40.999798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea5708e7e72d'
down_revision: Union[str, Sequence[str], None] = 'adc0352cad95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'moderator', name='user_role'), server_default='moderator', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('processing_logs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'fk_processing_logs_user_id_users',
        'processing_logs',
        'users',
        ['user_id'],
        ['id'],
    )
    op.add_column('shifts', sa.Column('confirmed_by_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'fk_shifts_confirmed_by_user_id_users',
        'shifts',
        'users',
        ['confirmed_by_user_id'],
        ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_shifts_confirmed_by_user_id_users', 'shifts', type_='foreignkey')
    op.drop_column('shifts', 'confirmed_by_user_id')
    op.drop_constraint('fk_processing_logs_user_id_users', 'processing_logs', type_='foreignkey')
    op.drop_column('processing_logs', 'user_id')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    sa.Enum(name='user_role').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
